SELECT 
    ENTEMP.NOMERESUMIDO AS EMPRESA,
    RELFUN.CODIGO,
    ENTFUN.NOMECOMPLETO,
    CARGO.DESCRICAO AS CARGO,
    ENTCON.NOMERESUMIDO AS CONVENCAO,
    ENTCON.ENTIDADE AS CODIGO2,
    FUNCIONARIO.DTADMISSAO
FROM FUNCIONARIO
    INNER JOIN RELACAOENTIDADE RELFUN 
        ON FUNCIONARIO.FUNCIONARIO = RELFUN.RELACAOENTIDADE 
        AND RELFUN.SITUACAO = 1

    INNER JOIN ENTIDADE ENTFUN 
        ON RELFUN.PAPEL1 = ENTFUN.ENTIDADE

    INNER JOIN RELACAOENTIDADE RELEMP 
        ON FUNCIONARIO.EMPRESA = RELEMP.RELACAOENTIDADE

    INNER JOIN ENTIDADE ENTEMP 
        ON RELEMP.PAPEL1 = ENTEMP.ENTIDADE

    LEFT JOIN CARGOFUNCIONARIOS 
        INNER JOIN CARGO 
            ON CARGOFUNCIONARIOS.CARGO = CARGO.CARGO 
            AND CARGO.SITUACAO = 1
        INNER JOIN RELACAOENTIDADE RELCON 
            ON CARGOFUNCIONARIOS.CONVENCAO = RELCON.RELACAOENTIDADE
        INNER JOIN ENTIDADE ENTCON 
            ON RELCON.PAPEL1 = ENTCON.ENTIDADE
        ON FUNCIONARIO.FUNCIONARIO = CARGOFUNCIONARIOS.FUNCIONARIO
        AND CARGOFUNCIONARIOS.DTINICIO <= '2025-01-01 00:00:00'
        AND (
            CARGOFUNCIONARIOS.DTFIM >= '2025-06-25 00:00:00'
            OR CARGOFUNCIONARIOS.DTFIM IS NULL
        )

WHERE 
    (
        FUNCIONARIO.DTDEMISSAO > '2025-01-01 00:00:00'
        OR FUNCIONARIO.DTDEMISSAO IS NULL
    )
ORDER BY 
    ENTEMP.NOMERESUMIDO,
    RELFUN.CODIGO;
