SELECT 
    ENTEMP.NOMERESUMIDO AS EMPRESA,
    RELFUN.CODIGO,
    ENTFUN.NOMECOMPLETO,
    CARGO.DESCRICAO AS CARGO,
    ENTCON.NOMERESUMIDO AS CONVENCAO,
    FUNCIONARIO.DTADMISSAO
FROM 
    FUNCIONARIO
    INNER JOIN RELACAOENTIDADE RELFUN 
        ON FUNCIONARIO.FUNCIONARIO = RELFUN.RELACAOENTIDADE
        AND RELFUN.SITUACAO = 1
    INNER JOIN ENTIDADE ENTFUN 
        ON RELFUN.PAPEL1 = ENTFUN.ENTIDADE
    INNER JOIN RELACAOENTIDADE RELEMP 
        ON FUNCIONARIO.EMPRESA = RELEMP.RELACAOENTIDADE
    INNER JOIN ENTIDADE ENTEMP 
        ON RELEMP.PAPEL1 = ENTEMP.ENTIDADE
    LEFT JOIN CARGOFUNCIONARIOS 
        ON FUNCIONARIO.FUNCIONARIO = CARGOFUNCIONARIOS.FUNCIONARIO
        AND CARGOFUNCIONARIOS.DTINICIO <= '2025-06-30'
        AND (CARGOFUNCIONARIOS.DTFIM >= '2025-06-30' OR CARGOFUNCIONARIOS.DTFIM IS NULL)
    LEFT JOIN CARGO 
        ON CARGOFUNCIONARIOS.CARGO = CARGO.CARGO
        AND CARGO.SITUACAO = 1
    LEFT JOIN RELACAOENTIDADE RELCON 
        ON CARGOFUNCIONARIOS.CONVENCAO = RELCON.RELACAOENTIDADE
    LEFT JOIN ENTIDADE ENTCON 
        ON RELCON.PAPEL1 = ENTCON.ENTIDADE
--WHERE  
--    EMPRESA LIKE '%BA%'
ORDER BY 
    ENTEMP.NOMERESUMIDO,
    RELFUN.CODIGO;

--SELECT * FROM RELATORIOSQL WHERE	RELATORIOSQL = 17833