SELECT 
    SARPRLOG.SARPRLOG,
    ENTEMP.NOMERESUMIDO AS NOMEEMPRESA,
    COALESCE(SARPRLOG.COLABORADOR, -1 * SARPRLOG.RE) AS COLABORADOR,
    SARPRLOG.RE AS REFUNCIONARIO,
    CASE 
        WHEN SARPRLOG.COLABORADOR IS NULL THEN 'FUNCIONÁRIO NÃO LOCALIZADO'
        ELSE ENTFUNC.NOMERESUMIDO
    END AS NOMEFUNCIONARIO,
    ENTCLI.NOMERESUMIDO AS NOMECLIENTEMARCACAO,
    ENTLOCAL.NOMERESUMIDO AS NOMELOCALSERVICOMARCACAO,
    TIPOALOCACAO.DESCRICAO AS DESCTIPOALOCACAO,
    --TPCOBERTURA.DESCRICAO AS DESCTIPOCOBERTURA,
    --SITMOBRAHJPONTO.DESCRICAO AS DESCSITHOJE,
    SITUACAOMOBRA.DESCRICAO AS DESCSITUACAOMOBRA,
    --PONTO.HRENTRADA,  
    --PONTO.HRSAIDA,
    CASE
        WHEN SARPRLOG.HKPONTOMENSAGENS IS NULL THEN SARPRMENSAGENS.DESCRICAOAPLICATIVO
        ELSE COALESCE(HKPONTOMENSAGENS.DESCRICAOEMPRESA, HKPONTOMENSAGENS.DESCRICAOORIGINAL)
    END AS DESCRETORNO,
    CASE
        WHEN SARPRLOG.RECOBERTURA = 0 THEN NULL
        ELSE SARPRLOG.RECOBERTURA
    END AS RECOBERTURA,
    SARPRLOG.DATAMARCACAO,
    SARPRLOG.DATASERVIDOR,
    SARPRLOG.CODRETORNO AS CODMARCACAO,
    EQUIPAMENTO.NUMEROFONE,
    EQUIPAMENTO.IMEI AS CHAVELICENCA,
    ATIVO.NUMEROPATRIMONIO AS PATRIMONIO,
    SARPRLOG.VAGAITEMCONTRATO,
    CASE
        WHEN SARPRLOG.SITMARCACAO = 2 THEN 1
        ELSE 0
    END AS ERROS,
    CASE SARPRLOG.SITMARCACAO
        WHEN 0 THEN 1
        WHEN 1 THEN 1
        ELSE 0
    END AS ACEITAS,
    CASE SARPRLOG.SITMARCACAO
        WHEN 0 THEN 'E'
        WHEN 1 THEN 'B'
        WHEN 2 THEN 'D'
    END AS SIGLASITMARCACAO,
    CASE SARPRLOG.TPCOMUNICACAO
        WHEN 1 THEN 'ON'
        ELSE 'OFF'
    END AS SIGLAOFFLINE,
    SARPRMETODOS.DESCRICAO AS DESCMETODO,
  --ENTAREA.NOMERESUMIDO AS AREASUPERVISAO,
    SARPRLOG.LATAPARELHO,
    SARPRLOG.LNGAPARELHO,
    SARPRLOG.LATLOCAL,
    SARPRLOG.LNGLOCAL,
    SARPRLOG.DISTANCIAMARCACAO

FROM 
    SARPRLOG
    INNER JOIN POSTOLOCALSERVICO ON POSTOLOCALSERVICO.POSTOLOCALSERVICO = SARPRLOG.POSTOLOCALSERVICO
    INNER JOIN LOCALSERVICOEMP ON LOCALSERVICOEMP.LOCALSERVICOEMP = POSTOLOCALSERVICO.LOCALSERVICOEMP
    INNER JOIN RELACAOENTIDADE RELEMP ON RELEMP.RELACAOENTIDADE = SARPRLOG.EMPRESA
    LEFT JOIN HKPONTOMENSAGENS ON HKPONTOMENSAGENS.HKPONTOMENSAGENS = SARPRLOG.HKPONTOMENSAGENS
    INNER JOIN ENTIDADE ENTEMP ON ENTEMP.ENTIDADE = RELEMP.PAPEL1
    INNER JOIN LOCALSERVICO ON LOCALSERVICO.LOCALSERVICO = LOCALSERVICOEMP.LOCALSERVICO
    LEFT JOIN SARPRMENSAGENS ON SARPRMENSAGENS.SARPRMENSAGENS = SARPRLOG.CODRETORNO
    INNER JOIN SARPRMETODOS ON SARPRMETODOS.SARPRMETODOS = SARPRLOG.CODMETODO
    LEFT OUTER JOIN RELACAOENTIDADE RELFUNC
        INNER JOIN ENTIDADE ENTFUNC ON ENTFUNC.ENTIDADE = RELFUNC.PAPEL1
    ON RELFUNC.RELACAOENTIDADE = SARPRLOG.COLABORADOR
    LEFT OUTER JOIN SITMAODEOBRAFUNC
        INNER JOIN SITUACAOMOBRA ON SITMAODEOBRAFUNC.SITUACAOMOBRATEMP = SITUACAOMOBRA.SITUACAOMOBRA
    ON SITMAODEOBRAFUNC.FUNCIONARIO = RELFUNC.RELACAOENTIDADE
        AND SITMAODEOBRAFUNC.SITUACAO = 1
        AND SITMAODEOBRAFUNC.DTINICIO <= SARPRLOG.DATAPONTO
        AND (SITMAODEOBRAFUNC.DTFIM IS NULL OR SITMAODEOBRAFUNC.DTFIM >= SARPRLOG.DATAPONTO)
    LEFT JOIN ATIVO ON ATIVO.ATIVO = SARPRLOG.IDAPARELHO
    LEFT JOIN EQUIPAMENTO ON EQUIPAMENTO.EQUIPAMENTO = ATIVO.ATIVO
    LEFT JOIN VAGAITEMCONTRATO
        INNER JOIN POSTOLOCALSERVICO POSTOVAGA ON VAGAITEMCONTRATO.POSTOLOCALSERVICO = POSTOVAGA.POSTOLOCALSERVICO
        INNER JOIN LOCALSERVICOEMP LOCALEMPVAGA ON POSTOVAGA.LOCALSERVICOEMP = LOCALEMPVAGA.LOCALSERVICOEMP
        INNER JOIN RELACAOENTIDADE RELLOCAL ON RELLOCAL.RELACAOENTIDADE = VAGAITEMCONTRATO.LOCALSERVICO
        INNER JOIN ENTIDADE ENTLOCAL ON ENTLOCAL.ENTIDADE = RELLOCAL.PAPEL1
        INNER JOIN RELACAOENTIDADE RELCLI ON RELCLI.RELACAOENTIDADE = VAGAITEMCONTRATO.CLIENTE
        INNER JOIN ENTIDADE ENTCLI ON ENTCLI.ENTIDADE = RELCLI.PAPEL1
        INNER JOIN RELACAOENTIDADE RELBASE ON RELBASE.RELACAOENTIDADE = VAGAITEMCONTRATO.BASEOPERACIONAL
        LEFT JOIN AREALOCALSERVICO ON AREALOCALSERVICO.LOCALSERVICOEMP = LOCALEMPVAGA.LOCALSERVICOEMP
            AND AREALOCALSERVICO.TURNOTRABALHO = VAGAITEMCONTRATO.TURNOTRABALHO
    ON VAGAITEMCONTRATO.VAGAITEMCONTRATO = SARPRLOG.VAGAITEMCONTRATO
    LEFT JOIN ALOCACAOMAODEOBRA ON VAGAITEMCONTRATO.VAGAITEMCONTRATO = ALOCACAOMAODEOBRA.VAGAITEMCONTRATO
        AND ALOCACAOMAODEOBRA.COLABORADOR = SARPRLOG.COLABORADOR
        AND ALOCACAOMAODEOBRA.SITALOCACAO = 1
        AND ALOCACAOMAODEOBRA.DTINICIO <= SARPRLOG.DATAPONTO
        AND (ALOCACAOMAODEOBRA.DTFIM IS NULL OR ALOCACAOMAODEOBRA.DTFIM >= SARPRLOG.DATAPONTO)
    LEFT JOIN DOMINIO TIPOALOCACAO ON TIPOALOCACAO.CHAVE = ALOCACAOMAODEOBRA.TPALOCACAO
        AND TIPOALOCACAO.TIPODOMINIO = 55
